// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALLd18gbMuLnPa2wF7D6WrND7InqQDgns',
    appId: '1:1048221436499:android:eddbe49bbc1ed07157d4a6',
    messagingSenderId: '1048221436499',
    projectId: 'fundtransport-a8c24',
    storageBucket: 'fundtransport-a8c24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHYibctayI0gfRPhfxSfmUPKxaZOS3NVQ',
    appId: '1:1048221436499:ios:c45c98ac3becd8b257d4a6',
    messagingSenderId: '1048221436499',
    projectId: 'fundtransport-a8c24',
    storageBucket: 'fundtransport-a8c24.appspot.com',
    iosBundleId: 'com.acb.fundtransport.app',
  );
}
